#!/bin/sh

# Credits: https://zakaria.org/posts/2021-01-04-xenodm.html

# set background
/usr/X11R6/bin/xsetroot -solid \#000000

# add Dina font to font list
/usr/X11R6/bin/xset fp+ /usr/local/share/fonts/dina

# status bar
(
while true; do
	reboot="%{F#b00035}%{A:reboot:} r %{A}%{F-}"
	shutdown="%{F#b00035}%{A:shutdown -p now:} p %{A}%{F-}"
	
	echo "  $(date '+%T') %{r}${reboot}/${shutdown}  $(date '+%F') "
	sleep 1
done | /usr/local/bin/lemonbar -d -g 1900x20+10+10 -f 'dinamedium8' -B \#000000 -F \#eeeeee | sh
) &
